package job.integration.sephora.tablesFetcher

/**
 * Created with IntelliJ IDEA.
 * User: spark
 * Date: 8/2/14
 * Time: 12:31 AM
 */
object Tables_Constantes{

  val PRODUITS_AXE_MAQUILLAGE = "MAQUILLAGE"
  val PRODUITS_AXE_PARFUM = "PARFUM"
  val PRODUITS_AXE_SOIN = "SOIN"
  val PRODUITS_MARKET_CODE_SEPHORA = "SEPHORA"
  val PRODUITS_MARKET_CODE_AUTRES = "AUTRES"
  val PRODUITS_MARKET_CODE_DIFFUSION = "DIFFUSION"
  val PRODUITS_MARKET_CODE_EMERGENT = "EMERGENT"
  val PRODUITS_MARKET_CODE_SPLUSMARQUEPR = "S+MARQUEPR"
  val PRODUITS_MARKET_CODE_SELECTIF = "SELECTIF"
}
